apiVersion: v2
description: A Helm chart for the HMCTS CCD Message Publisher
name: ccd-message-publisher
home: https://github.com/hmcts/ccd-message-publisher
version: 0.0.6
maintainers:
  - name: HMCTS CCD Dev Team
dependencies:
  - name: java
    version: 3.4.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: servicebus
    version: 0.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: servicebus.enabled
