java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
  environment:
    DATA_STORE_DB_HOST: ccd-data-store-api-pr-1260-postgresql
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
    CCD_CASE_EVENTS_DESTINATION: ccd-case-events
  secrets:
    SERVICE_BUS_CONNECTION_STRING:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-ccd-case-events
      key: connectionString

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: ccd-aks
  serviceplan: standard
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes

global:
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
  dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
  ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
  ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
  ccdCaseManagementWebIngress: case-management-web-${SERVICE_FQDN}
  postgresUsername: hmcts
  postgresPassword: hmcts
  s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

ccd-data-store-api:
  java:
    image: 'hmctspublic.azurecr.io/ccd/data-store-api:latest'
    imagePullPolicy: Always
    applicationPort: 5432
    environment:
      DATA_STORE_DB_NAME: "data-store"
      DATA_STORE_DB_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      DATA_STORE_DB_PASSWORD: '{{ tpl .Values.global.postgresPassword $}}'
      DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
      DATA_STORE_DB_MAX_POOL_SIZE: 10
      CCD_DM_DOMAIN: https?://dm-store.*
      IDAM_USER_URL: '{{ tpl .Values.global.idamWebUrl $}}'
      IDAM_S2S_URL: '{{ tpl .Values.global.s2sUrl $}}'
      DATA_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DEFINITION_STORE_HOST: '{{ tpl .Values.global.ccdDefinitionStoreUrl $}}'
      USER_PROFILE_HOST: '{{ tpl .Values.global.ccdUserProfileUrl $}}'
      CCD_DRAFT_STORE_URL: '{{ tpl .Values.global.draftStoreUrl $}}'
      ENABLE_DB_MIGRATE: true
      ELASTIC_SEARCH_ENABLED: false
      ELASTIC_SEARCH_NODES_DISCOVERY_ENABLED: false
