java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
  environment:
    DATA_STORE_DB_HOST: ccd-data-store-api-pr-1260-postgresql
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
    CCD_CASE_EVENTS_DESTINATION: ccd-case-events
  secrets:
    SERVICE_BUS_CONNECTION_STRING:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-ccd-case-events
      key: connectionString

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: ccd-aks
  serviceplan: standard
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
ccd:
  ccd:
    definitionImporter:
      enabled: false
    managementWeb:
      enabled: false
    apiGatewayWeb:
      enabled: false
    adminWeb:
      enabled: false
    s2s:
      enabled: false
    userProfileImporter:
      enabled: false
  
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    ccdCaseManagementWebIngress: case-management-web-${SERVICE_FQDN}
    postgresUsername: hmcts
    postgresPassword: hmcts
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}

  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      keyVaults: []
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_admin,ccd_data,divorce,ccd_gw,divorce_ccd_submission
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
      ingressHost: ccd-definition-store-${SERVICE_FQDN}

  postgresql:
    persistence:
      enabled: false