java:
  applicationPort: 4456
  image: 'hmctspublic.azurecr.io/ccd/message-publisher:latest'
  ingressHost: ccd-message-publisher-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccd
  replicas: 1 # Must always be 1
  keyVaults:
    ccd:
      secrets:
        - data-store-api-POSTGRES-PASS
        - ccd-servicebus-connection-string
        - AppInsightsInstrumentationKey
  environment:
    DATA_STORE_DB_PORT: 5432
    DATA_STORE_DB_NAME: ccd_data_store
    DATA_STORE_DB_HOST: ccd-data-store-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    DATA_STORE_DB_USERNAME: ccd@ccd-data-store-api-postgres-db-{{ .Values.global.environment }}
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&sslmode=require&gssEncMode=disable"
    CCD_CASE_EVENTS_DESTINATION: ccd-case-events-{{ .Values.global.environment }}

servicebus:
  enabled: false
