java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
  environment:
    DATA_STORE_DB_HOST: ccd-data-store-api-pr-1260-postgresql
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
    CCD_CASE_EVENTS_DESTINATION: ccd-case-events
  secrets:
    SERVICE_BUS_CONNECTION_STRING:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-ccd-case-events
      key: connectionString

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: ccd-aks
  serviceplan: standard
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
