java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
  environment:
    SPRING_PROFILES_ACTIVE: dev
    DATA_STORE_DB_HOST: ccd-data-store-api-pr-601-postgresql
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
