java:
  applicationPort: 4456
  image: 'hmctspublic.azurecr.io/ccd/message-publisher:latest'
  ingressHost: ccd-message-publisher-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccd
  replicas: 1 # Must always be 1
  keyVaults:
    ccd:
      secrets:
        - data-store-api-POSTGRES-PASS
        - ccd-servicebus-connection-string
        - AppInsightsInstrumentationKey
  environment:
    DATA_STORE_DB_PORT: 5432
    DATA_STORE_DB_NAME: ccd_data_store
    DATA_STORE_DB_HOST: ccd-data-store-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    DATA_STORE_DB_USERNAME: ccd@ccd-data-store-api-postgres-db-{{ .Values.global.environment }}
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&sslmode=require&gssEncMode=disable"
    CCD_CASE_EVENTS_DESTINATION: ccd-case-events-{{ .Values.global.environment }}

servicebus:
  enabled: false

ccd-data-store-api:
  java:
    image: 'hmctspublic.azurecr.io/ccd/data-store-api:latest'
    imagePullPolicy: Always
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-ccd-data-store-api"
    readinessDelay: 240
    livenessDelay: 240
    environment:
      DATA_STORE_DB_NAME: "data-store"
      DATA_STORE_DB_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      DATA_STORE_DB_PASSWORD: '{{ tpl .Values.global.postgresPassword $}}'
      DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
      DATA_STORE_DB_MAX_POOL_SIZE: 10
      CCD_DM_DOMAIN: https?://dm-store.*
      IDAM_USER_URL: '{{ tpl .Values.global.idamWebUrl $}}'
      IDAM_S2S_URL: '{{ tpl .Values.global.s2sUrl $}}'
      DATA_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DEFINITION_STORE_HOST: '{{ tpl .Values.global.ccdDefinitionStoreUrl $}}'
      USER_PROFILE_HOST: '{{ tpl .Values.global.ccdUserProfileUrl $}}'
      CCD_DRAFT_STORE_URL: '{{ tpl .Values.global.draftStoreUrl $}}'
      ENABLE_DB_MIGRATE: true
      ELASTIC_SEARCH_ENABLED: false
      ELASTIC_SEARCH_NODES_DISCOVERY_ENABLED: false

global:
  idamApiUrl: ""
  idamWebUrl: ""
  ccdDataStoreUrl: "http://{{ .Release.Name }}-ccd-data-store-api"
  ccdDefinitionStoreUrl: "http://{{ .Release.Name }}-ccd-definition-store"
  ccdUserProfileUrl: "http://{{ .Release.Name }}-ccd-user-profile-api"
  draftStoreUrl: "http://{{ .Release.Name }}-draft-store"
  s2sUrl: "http://{{ .Release.Name }}-s2s"
  postgresUsername: hmcts
  postgresPassword: hmcts
